package fr.angel.dynamicisland.ui.theme.themes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val md_theme_quinacridone_magenta_light_primary = Color(0xFF984061)
val md_theme_quinacridone_magenta_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_quinacridone_magenta_light_primaryContainer = Color(0xFFFFD9E2)
val md_theme_quinacridone_magenta_light_onPrimaryContainer = Color(0xFF3E001D)
val md_theme_quinacridone_magenta_light_secondary = Color(0xFF74565F)
val md_theme_quinacridone_magenta_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_quinacridone_magenta_light_secondaryContainer = Color(0xFFFFD9E2)
val md_theme_quinacridone_magenta_light_onSecondaryContainer = Color(0xFF2B151C)
val md_theme_quinacridone_magenta_light_tertiary = Color(0xFF7C5635)
val md_theme_quinacridone_magenta_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_quinacridone_magenta_light_tertiaryContainer = Color(0xFFFFDCC2)
val md_theme_quinacridone_magenta_light_onTertiaryContainer = Color(0xFF2E1500)
val md_theme_quinacridone_magenta_light_error = Color(0xFFBA1A1A)
val md_theme_quinacridone_magenta_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_quinacridone_magenta_light_onError = Color(0xFFFFFFFF)
val md_theme_quinacridone_magenta_light_onErrorContainer = Color(0xFF410002)
val md_theme_quinacridone_magenta_light_background = Color(0xFFFFFBFF)
val md_theme_quinacridone_magenta_light_onBackground = Color(0xFF201A1B)
val md_theme_quinacridone_magenta_light_surface = Color(0xFFFFFBFF)
val md_theme_quinacridone_magenta_light_onSurface = Color(0xFF201A1B)
val md_theme_quinacridone_magenta_light_surfaceVariant = Color(0xFFF2DDE2)
val md_theme_quinacridone_magenta_light_onSurfaceVariant = Color(0xFF514347)
val md_theme_quinacridone_magenta_light_outline = Color(0xFF837377)
val md_theme_quinacridone_magenta_light_inverseOnSurface = Color(0xFFFAEEEF)
val md_theme_quinacridone_magenta_light_inverseSurface = Color(0xFF352F30)
val md_theme_quinacridone_magenta_light_inversePrimary = Color(0xFFFFB0C8)
val md_theme_quinacridone_magenta_light_shadow = Color(0xFF000000)
val md_theme_quinacridone_magenta_light_surfaceTint = Color(0xFF984061)
val md_theme_quinacridone_magenta_light_outlineVariant = Color(0xFFD5C2C6)
val md_theme_quinacridone_magenta_light_scrim = Color(0xFF000000)

val md_theme_quinacridone_magenta_dark_primary = Color(0xFFFFB0C8)
val md_theme_quinacridone_magenta_dark_onPrimary = Color(0xFF5E1133)
val md_theme_quinacridone_magenta_dark_primaryContainer = Color(0xFF7B2949)
val md_theme_quinacridone_magenta_dark_onPrimaryContainer = Color(0xFFFFD9E2)
val md_theme_quinacridone_magenta_dark_secondary = Color(0xFFE2BDC6)
val md_theme_quinacridone_magenta_dark_onSecondary = Color(0xFF422931)
val md_theme_quinacridone_magenta_dark_secondaryContainer = Color(0xFF5A3F47)
val md_theme_quinacridone_magenta_dark_onSecondaryContainer = Color(0xFFFFD9E2)
val md_theme_quinacridone_magenta_dark_tertiary = Color(0xFFEFBD94)
val md_theme_quinacridone_magenta_dark_onTertiary = Color(0xFF48290C)
val md_theme_quinacridone_magenta_dark_tertiaryContainer = Color(0xFF623F20)
val md_theme_quinacridone_magenta_dark_onTertiaryContainer = Color(0xFFFFDCC2)
val md_theme_quinacridone_magenta_dark_error = Color(0xFFFFB4AB)
val md_theme_quinacridone_magenta_dark_errorContainer = Color(0xFF93000A)
val md_theme_quinacridone_magenta_dark_onError = Color(0xFF690005)
val md_theme_quinacridone_magenta_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_quinacridone_magenta_dark_background = Color(0xFF201A1B)
val md_theme_quinacridone_magenta_dark_onBackground = Color(0xFFEBE0E1)
val md_theme_quinacridone_magenta_dark_surface = Color(0xFF201A1B)
val md_theme_quinacridone_magenta_dark_onSurface = Color(0xFFEBE0E1)
val md_theme_quinacridone_magenta_dark_surfaceVariant = Color(0xFF514347)
val md_theme_quinacridone_magenta_dark_onSurfaceVariant = Color(0xFFD5C2C6)
val md_theme_quinacridone_magenta_dark_outline = Color(0xFF9E8C90)
val md_theme_quinacridone_magenta_dark_inverseOnSurface = Color(0xFF201A1B)
val md_theme_quinacridone_magenta_dark_inverseSurface = Color(0xFFEBE0E1)
val md_theme_quinacridone_magenta_dark_inversePrimary = Color(0xFF984061)
val md_theme_quinacridone_magenta_dark_shadow = Color(0xFF000000)
val md_theme_quinacridone_magenta_dark_surfaceTint = Color(0xFFFFB0C8)
val md_theme_quinacridone_magenta_dark_outlineVariant = Color(0xFF514347)
val md_theme_quinacridone_magenta_dark_scrim = Color(0xFF000000)

val quinacridone_magenta_seed = Color(0xFF984061)

val QuinacridoneMagentaThemeLightColors = lightColorScheme(
	primary = md_theme_quinacridone_magenta_light_primary,
	onPrimary = md_theme_quinacridone_magenta_light_onPrimary,
	primaryContainer = md_theme_quinacridone_magenta_light_primaryContainer,
	onPrimaryContainer = md_theme_quinacridone_magenta_light_onPrimaryContainer,
	secondary = md_theme_quinacridone_magenta_light_secondary,
	onSecondary = md_theme_quinacridone_magenta_light_onSecondary,
	secondaryContainer = md_theme_quinacridone_magenta_light_secondaryContainer,
	onSecondaryContainer = md_theme_quinacridone_magenta_light_onSecondaryContainer,
	tertiary = md_theme_quinacridone_magenta_light_tertiary,
	onTertiary = md_theme_quinacridone_magenta_light_onTertiary,
	tertiaryContainer = md_theme_quinacridone_magenta_light_tertiaryContainer,
	onTertiaryContainer = md_theme_quinacridone_magenta_light_onTertiaryContainer,
	error = md_theme_quinacridone_magenta_light_error,
	errorContainer = md_theme_quinacridone_magenta_light_errorContainer,
	onError = md_theme_quinacridone_magenta_light_onError,
	onErrorContainer = md_theme_quinacridone_magenta_light_onErrorContainer,
	background = md_theme_quinacridone_magenta_light_background,
	onBackground = md_theme_quinacridone_magenta_light_onBackground,
	surface = md_theme_quinacridone_magenta_light_surface,
	onSurface = md_theme_quinacridone_magenta_light_onSurface,
	surfaceVariant = md_theme_quinacridone_magenta_light_surfaceVariant,
	onSurfaceVariant = md_theme_quinacridone_magenta_light_onSurfaceVariant,
	outline = md_theme_quinacridone_magenta_light_outline,
	inverseOnSurface = md_theme_quinacridone_magenta_light_inverseOnSurface,
	inverseSurface = md_theme_quinacridone_magenta_light_inverseSurface,
	inversePrimary = md_theme_quinacridone_magenta_light_inversePrimary,
	surfaceTint = md_theme_quinacridone_magenta_light_surfaceTint,
	outlineVariant = md_theme_quinacridone_magenta_light_outlineVariant,
	scrim = md_theme_quinacridone_magenta_light_scrim,
)


val QuinacridoneMagentaThemeDarkColors = darkColorScheme(
	primary = md_theme_quinacridone_magenta_dark_primary,
	onPrimary = md_theme_quinacridone_magenta_dark_onPrimary,
	primaryContainer = md_theme_quinacridone_magenta_dark_primaryContainer,
	onPrimaryContainer = md_theme_quinacridone_magenta_dark_onPrimaryContainer,
	secondary = md_theme_quinacridone_magenta_dark_secondary,
	onSecondary = md_theme_quinacridone_magenta_dark_onSecondary,
	secondaryContainer = md_theme_quinacridone_magenta_dark_secondaryContainer,
	onSecondaryContainer = md_theme_quinacridone_magenta_dark_onSecondaryContainer,
	tertiary = md_theme_quinacridone_magenta_dark_tertiary,
	onTertiary = md_theme_quinacridone_magenta_dark_onTertiary,
	tertiaryContainer = md_theme_quinacridone_magenta_dark_tertiaryContainer,
	onTertiaryContainer = md_theme_quinacridone_magenta_dark_onTertiaryContainer,
	error = md_theme_quinacridone_magenta_dark_error,
	errorContainer = md_theme_quinacridone_magenta_dark_errorContainer,
	onError = md_theme_quinacridone_magenta_dark_onError,
	onErrorContainer = md_theme_quinacridone_magenta_dark_onErrorContainer,
	background = md_theme_quinacridone_magenta_dark_background,
	onBackground = md_theme_quinacridone_magenta_dark_onBackground,
	surface = md_theme_quinacridone_magenta_dark_surface,
	onSurface = md_theme_quinacridone_magenta_dark_onSurface,
	surfaceVariant = md_theme_quinacridone_magenta_dark_surfaceVariant,
	onSurfaceVariant = md_theme_quinacridone_magenta_dark_onSurfaceVariant,
	outline = md_theme_quinacridone_magenta_dark_outline,
	inverseOnSurface = md_theme_quinacridone_magenta_dark_inverseOnSurface,
	inverseSurface = md_theme_quinacridone_magenta_dark_inverseSurface,
	inversePrimary = md_theme_quinacridone_magenta_dark_inversePrimary,
	surfaceTint = md_theme_quinacridone_magenta_dark_surfaceTint,
	outlineVariant = md_theme_quinacridone_magenta_dark_outlineVariant,
	scrim = md_theme_quinacridone_magenta_dark_scrim,
)